config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :comments
  resources :blogposts

	root 'blogposts#index'
	get 'hello' => 'application#hello'
end

app/models/blogpost.rb
class Blogpost < ActiveRecord::Base
	has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :blogpost
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

def hello
	render text: "hello world!"
end
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
  before_action :set_blogpost, only: [:show, :edit, :update, :destroy]

  # GET /blogposts
  # GET /blogposts.json
  def index
    @blogposts = Blogpost.all
  end

  # GET /blogposts/1
  # GET /blogposts/1.json
  def show
	@bpcomments = @blogpost.comments
  end

  # GET /blogposts/new
  def new
    @blogpost = Blogpost.new
  end

  # GET /blogposts/1/edit
  def edit
  end

  # POST /blogposts
  # POST /blogposts.json
  def create
    @blogpost = Blogpost.new(blogpost_params)

    respond_to do |format|
      if @blogpost.save
        format.html { redirect_to @blogpost, notice: 'Blogpost was successfully created.' }
        format.json { render :show, status: :created, location: @blogpost }
      else
        format.html { render :new }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogposts/1
  # PATCH/PUT /blogposts/1.json
  def update
    respond_to do |format|
      if @blogpost.update(blogpost_params)
        format.html { redirect_to @blogpost, notice: 'Blogpost was successfully updated.' }
        format.json { render :show, status: :ok, location: @blogpost }
      else
        format.html { render :edit }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogposts/1
  # DELETE /blogposts/1.json
  def destroy
    @blogpost.destroy
    respond_to do |format|
      format.html { redirect_to blogposts_url, notice: 'Blogpost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blogpost
      @blogpost = Blogpost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blogpost_params
      params.require(:blogpost).permit(:title, :contents)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:commenttext, :author, :blogpost_id, :integer)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blogposts/_form.html.erb
<%= form_for(@blogpost) do |f| %>
  <% if @blogpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blogpost.errors.count, "error") %> prohibited this blogpost from being saved:</h2>

      <ul>
      <% @blogpost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :contents %><br>
    <%= f.text_area :contents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogposts/edit.html.erb
<h1>Editing Blogpost</h1>

<%= render 'form' %>

<%= link_to 'Show', @blogpost %> |
<%= link_to 'Back', blogposts_path %>

app/views/blogposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blogposts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Contents</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogposts.each do |blogpost| %>
      <tr>
        <td><%= blogpost.title %></td>
        <td><%= blogpost.contents %></td>
        <td><%= link_to 'Show', blogpost %></td>
        <td><%= link_to 'Edit', edit_blogpost_path(blogpost) %></td>
        <td><%= link_to 'Destroy', blogpost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blogpost', new_blogpost_path %>

app/views/blogposts/new.html.erb
<h1>New Blogpost</h1>

<%= render 'form' %>

<%= link_to 'Back', blogposts_path %>

app/views/blogposts/show.html.erb
<p id="notice"><%= notice %></p>
<div class= "boxed">  
<h1>
  <%= @blogpost.title %>
</h1>

<p>
  <%= @blogpost.contents %>
</p>
</div>

<%= link_to 'Edit', edit_blogpost_path(@blogpost) %> |
<%= link_to 'Back', blogposts_path %>

<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Commenttext</th>
      <th>Author</th>
      <th>Blogpost</th>
      <th>Integer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bpcomments.each do |comment| %>
      <tr>
        <td><%= comment.commenttext %></td>
        <td><%= comment.author %></td>
        <td><%= comment.blogpost_id %></td>
        <td><%= comment.integer %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :commenttext %><br>
    <%= f.text_area :commenttext %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :blogpost_id %><br>
    <%= f.text_field :blogpost_id %>
  </div>
  <div class="field">
    <%= f.label :integer %><br>
    <%= f.text_field :integer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Commenttext</th>
      <th>Author</th>
      <th>Blogpost</th>
      <th>Integer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.commenttext %></td>
        <td><%= comment.author %></td>
        <td><%= comment.blogpost_id %></td>
        <td><%= comment.integer %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Commenttext:</strong>
  <%= @comment.commenttext %>
</p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Blogpost:</strong>
  <%= @comment.blogpost_id %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @comment.integer %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>